image_width: 1920
image_height: 1080
camera_name: usb_cam
camera_matrix:
  rows: 3
  cols: 3
  data: [1368.9, 0, 949.29, 0, 1368.8, 518.06, 0, 0, 1]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.22521, -0.55961, -0.00056151, 0.00076246, 0.37664]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1, 0, 0, 0, 1, 0, 0, 0, 1]
projection_matrix:
  rows: 3
  cols: 4
  data: [1368.9, 0, 949.29, 0, 0, 1368.8, 518.06, 0, 0, 0, 1, 0]
